### ДЗ


1.   Обучите сеть без скрытых слоев (постройте аналог обычной линейной модели). Какое accuracy вы получили на валидации?
2.   Обучите сеть с двумя скрытыми слоями по 128 нейронов в каждом. Какое accuracy на валидации получили?




In [1]:
!pip install tensorflow==2.11.0

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.3/588.3 MB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 45.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 32.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 63.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.2/439.2 kB 21.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 52.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.3/781.3 kB 29.5 MB/s eta 0:00:00
  Attempting uninstall: tensorboard-data-server
    Found existing installation: tensorboard-data-server 0.7.2
    Uninstalling tensorboard-data-server-0.7.2:
      Successfully uninstalled tensorboard-data-server-0.7.2
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20.3
  Attempting uninstall: keras
    Found existing installation: kera

In [2]:
!pip install keras==2.11.0

In [3]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.backend import clear_session
import numpy as np
import pandas as pd
import sklearn
from sklearn.metrics import accuracy_score

In [4]:
(x_train, y_train), (x_val, y_val) = tf.keras.datasets.mnist.load_data()
print(x_train.shape)
print(x_val.shape)
print(y_train[:10])
print(y_val[:10])

11490434/11490434 [==============================] - 0s 0us/step
(60000, 28, 28)
(10000, 28, 28)
[5 0 4 1 9 2 1 3 1 4]
[7 2 1 0 4 1 4 9 5 9]


In [8]:
x_train_flat = x_train.reshape(-1, 28*28).astype(float)
print(x_train.shape, x_train_flat.shape)

x_val_flat = x_val.reshape(-1, 28*28).astype(float)
print(x_val.shape, x_val_flat.shape)

(60000, 28, 28) (60000, 784)
(10000, 28, 28) (10000, 784)


In [9]:
x_train_float = x_train_flat.astype(float) / 255 - 0.5
x_val_float = x_val_flat.astype(float) / 255 - 0.5

y_train_oh = keras.utils.to_categorical(y_train, 10)
y_val_oh = keras.utils.to_categorical(y_val, 10)

print(y_train_oh.shape)
print(y_train_oh[:5], y_train[:5])

(60000, 10)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]] [5 0 4 1 9]


In [13]:
clear_session()

In [14]:
# Архитектура сети
model = Sequential()

# Выходной слой (Dense): 10 нейронов (по одному для каждого класса), активация softmax для предсказания вероятностей
model.add(Dense(10, activation='softmax', input_shape=(x_train_float.shape[1],))) # выходной слой

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                7850      
                                                                 
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [17]:
history = model.fit(
                    x_train_float,
                    y_train_oh,
                    batch_size=64,
                    epochs=10,
                    validation_data=(x_val_float, y_val_oh)
                    )

Epoch 1/10
938/938 [==============================] - 4s 3ms/step - loss: 0.5719 - accuracy: 0.8472 - val_loss: 0.3512 - val_accuracy: 0.9037
Epoch 2/10
938/938 [==============================] - 2s 2ms/step - loss: 0.3467 - accuracy: 0.9011 - val_loss: 0.3069 - val_accuracy: 0.9134
Epoch 3/10
938/938 [==============================] - 3s 3ms/step - loss: 0.3190 - accuracy: 0.9091 - val_loss: 0.2950 - val_accuracy: 0.9148
Epoch 4/10
938/938 [==============================] - 3s 4ms/step - loss: 0.3070 - accuracy: 0.9122 - val_loss: 0.2917 - val_accuracy: 0.9185
Epoch 5/10
938/938 [==============================] - 2s 3ms/step - loss: 0.2981 - accuracy: 0.9152 - val_loss: 0.2893 - val_accuracy: 0.9185
Epoch 6/10
938/938 [==============================] - 2s 2ms/step - loss: 0.2931 - accuracy: 0.9173 - val_loss: 0.2838 - val_accuracy: 0.9175
Epoch 7/10
938/938 [==============================] - 2s 3ms/step - loss: 0.2893 - accuracy: 0.9182 - val_loss: 0.2843 - val_accuracy: 0.9213
Epoch 

In [18]:
# Прогнозируем метки классов для валидационных данных
predicts = np.argmax(model.predict(x_val_float), axis = 1)

# Выводим точность на тестовых (валидационных) данных
print('Test Accuracy: ', accuracy_score(y_val, predicts))

313/313 [==============================] - 1s 4ms/step
Test Accuracy:  0.9202


In [19]:
model = Sequential() # Определяем модель как последовательную (слои добавляются один за другим)

# Первый скрытый слой (Dense): 128 нейронов, активация ReLU
# Input_shape задает размер входных данных (размерность признаков), равный числу пикселей (784)
model.add(Dense(128, activation='relu', input_shape=(x_train_float.shape[1],)))

# Второй скрытый слой (Dense): 128 нейронов, активация ReLU
model.add(Dense(128, activation='relu',))

# Выходной слой (Dense): 10 нейронов (по одному для каждого класса), активация softmax для предсказания вероятностей
model.add(Dense(10, activation='softmax',)) # выходной слой

In [21]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 128)               100480    
                                                                 
 dense_2 (Dense)             (None, 128)               16512     
                                                                 
 dense_3 (Dense)             (None, 10)                1290      
                                                                 
Total params: 118,282
Trainable params: 118,282
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.compile(
    loss='categorical_crossentropy',  # минимизируем кросс-энтропию
    optimizer='adam',  # так будет быстрее, позже узнаем что это :)
    metrics=['accuracy']  # выводим процент правильных ответов
)

In [22]:
history = model.fit(
                    x_train_float,
                    y_train_oh,
                    batch_size=64,  # 64 объекта для подсчета градиента на каждом шаге
                    epochs=10,  # 10 проходов по датасету
                    validation_data=(x_val_float, y_val_oh)
                    )

Epoch 1/10
938/938 [==============================] - 9s 8ms/step - loss: 0.3478 - accuracy: 0.8944 - val_loss: 0.2023 - val_accuracy: 0.9391
Epoch 2/10
938/938 [==============================] - 8s 9ms/step - loss: 0.1612 - accuracy: 0.9512 - val_loss: 0.1378 - val_accuracy: 0.9568
Epoch 3/10
938/938 [==============================] - 5s 6ms/step - loss: 0.1239 - accuracy: 0.9619 - val_loss: 0.1314 - val_accuracy: 0.9595
Epoch 4/10
938/938 [==============================] - 7s 8ms/step - loss: 0.1019 - accuracy: 0.9690 - val_loss: 0.0973 - val_accuracy: 0.9697
Epoch 5/10
938/938 [==============================] - 5s 6ms/step - loss: 0.0854 - accuracy: 0.9731 - val_loss: 0.1022 - val_accuracy: 0.9683
Epoch 6/10
938/938 [==============================] - 6s 7ms/step - loss: 0.0744 - accuracy: 0.9763 - val_loss: 0.0931 - val_accuracy: 0.9722
Epoch 7/10
938/938 [==============================] - 6s 7ms/step - loss: 0.0650 - accuracy: 0.9790 - val_loss: 0.0803 - val_accuracy: 0.9760
Epoch 

In [23]:
# Прогнозируем метки классов для валидационных данных
predicts = np.argmax(model.predict(x_val_float), axis = 1)

# Выводим точность на тестовых (валидационных) данных
print('Test Accuracy: ', accuracy_score(y_val, predicts))

313/313 [==============================] - 2s 5ms/step
Test Accuracy:  0.9763
